plugin: netbox.netbox.nb_inventory
api_endpoint: "{{ lookup('env', 'NETBOX_URL') }}"
token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
validate_certs: "{{ lookup('env', 'NETBOX_VALIDATE_CERTS') | default('true', true) | bool }}"

group_by:
  - device_roles

compose:
  ansible_host: primary_ip.address | ipaddr('address')
  loopback_ip: interfaces | selectattr('name', 'equalto', 'lo') | map(attribute='ip_addresses') | first | first | attr('address') | ipaddr('address')

config_context: true
