plugin: netbox.netbox.nb_inventory

group_by:
  - device_roles

compose:
  ansible_user: custom_fields.ansible_user
  ansible_host: primary_ip.address | ipaddr('address')
  loopback_ip: custom_fields.loopback_ip | ipaddr('address')

config_context: true
