---
# Default variables for GRE role
# Role used in NetBox to tag /31 prefixes for GRE tunnels
gre_tunnel_prefix_role: gre-tunnels

# Local file containing /31 prefixes to skip during GRE allocation.
gre_blocked_prefixes_file: "{{ inventory_dir }}/gre_blocked_prefixes_10.255.0.0_23.txt"
